-- Extension description
function descriptor()
  return {
    title = "Load Time";
    version = "1.0";
    author = "Parker Miller";
    shortdesc = "Load elapsed time.";
    description = "If a log file was generated by Save Time then this will set the current elapsed time to what was logged.";
  }
end

function activate()
  local input = vlc.object.input()
  if input then
    local uri = vlc.strings.decode_uri(vlc.input.item():uri()) -- Format: file:///dir1/dir2/file.ext
    local filePath = string.gsub(uri, "file:///", "")          -- Format: dir1/dir2/file.ext
    local directory = string.gsub(filePath, "/[^/]*$", "")     -- Format: dir1/dir2         Remove last / and everything after it to leave the directory.
    local file = io.open(directory .. "/" .. vlc.input.item():name() .. ".txt", "r")

    if (file == nil) then
      vlc.msg.err("No log file to load.")
      return
    end

    local elapsedTime = file:read()
    io.close()

    vlc.var.set(input, "time", elapsedTime-5) -- We go back 5 seconds to add more context.
  end
  deactivate()
end
